-- Kitchenmayhem — Half-Sword UE4SS Mod
-- Generated by Grok Half-Sword Mod Factory (hsmod)
-- "Everyone gets kitchen tools" — Frying pans, rolling pins, cleavers & chaos
--
-- This script registers powerful console commands.
-- Requires UE4SS 3.x installed in the game Binaries/Win64 folder.
--
-- How to use:
--   1. Copy the folder containing this file into:
--      HalfswordUE5/Binaries/Win64/UE4SS/Mods/KitchenMayhem/
--   2. Launch the game.
--   3. Open the console (usually ~ or Insert) and type the commands below.
--
-- Safe patterns used: FindFirstOf for WorldSettings / Willie_BP_C,
-- direct property assignment, print feedback.


local function ApplyTimeDilation(factor)
    local ws = FindFirstOf("WorldSettings")
    if ws and ws:IsValid() then
        ws.TimeDilation = factor
        print(string.format("[Chef] TimeDilation set to %.2fx", factor))
    else
        print("[Chef] Could not find WorldSettings")
    end
end

local function BuffPlayerHealth(amount)
    local player = FindFirstOf("Willie_BP_C")
    if player and player:IsValid() then
        player.Health = math.min(200.0, (player.Health or 100.0) + amount)
        print(string.format("[Chef] Player health buffed (+%.0f)", amount))
    else
        print("[Chef] Player (Willie_BP_C) not found in current context")
    end
end

local function BuffMusclePower(amount)
    local player = FindFirstOf("Willie_BP_C")
    if player and player:IsValid() then
        player["Muscle Power"] = (player["Muscle Power"] or 1.0) + amount
        print(string.format("[Chef] Pan-swing power increased! (+%.1f)", amount))
    end
end

local function Cmd_ChefSlow()
    ApplyTimeDilation(0.3)
end
local function Cmd_ChefFast()
    ApplyTimeDilation(1.8)
end
local function Cmd_ChefNormal()
    ApplyTimeDilation(1.0)
end
local function Cmd_IronChef()
    BuffPlayerHealth(75)
    BuffMusclePower(0.4)
    print("[Chef] FULL Iron Chef MODE ACTIVATED!")
end
local function Cmd_PanTime()
    ApplyTimeDilation(0.15)
    print("[Chef] PAN TIME! Everything moves like it's simmering in slow motion oil!")
end

local function Cmd_RatatouilleRage()
    BuffPlayerHealth(50)
    BuffMusclePower(0.6)
    print("[Chef] RATATOUILLE RAGE! The little rat inside you has taken over!")
end

local function Cmd_SpatulaSlap()
    BuffMusclePower(0.3)
    print("[Chef] You feel the power of the mighty spatula! Slap them into next Tuesday!")
end

-- === Command Registration ===
RegisterConsoleCommand("ChefSlow", Cmd_ChefSlow)  -- Dramatic slow-mo for cooking moments
RegisterConsoleCommand("ChefFast", Cmd_ChefFast)  -- Faster action
RegisterConsoleCommand("ChefNormal", Cmd_ChefNormal)  -- Reset to normal speed
RegisterConsoleCommand("IronChef", Cmd_IronChef)  -- Full Iron Chef mode (health + power)
RegisterConsoleCommand("PanTime", Cmd_PanTime)  -- Ultra dramatic 'Pan Time'
RegisterConsoleCommand("RatatouilleRage", Cmd_RatatouilleRage)  -- Embrace your inner rat chef
RegisterConsoleCommand("SpatulaSlap", Cmd_SpatulaSlap)  -- Channel the power of the spatula

print("[Kitchenmayhem] Kitchen Mayhem mod fully loaded and ready.")

-- === Full Game-Changing "Kitchen Dystopia" Mode (entire game feel) ===
local dystopiaActive = false

local function ToggleKitchenDystopia()
    dystopiaActive = not dystopiaActive
    if dystopiaActive then
        ApplyTimeDilation(0.55)
        print("========================================")
        print("[CHEF APOCALYPSE] KITCHEN DYSTOPIA MODE ACTIVATED!")
        print("[CHEF APOCALYPSE] The entire world is now a ruined post-apocalyptic kitchen.")
        print("[CHEF APOCALYPSE] Time is warped. Everyone is a chef. Fight with pans.")
        print("========================================")
    else
        ApplyTimeDilation(1.0)
        print("[CHEF APOCALYPSE] Dystopia mode ended. The kitchen returns to normal chaos.")
    end
end

RegisterConsoleCommand("KitchenDystopia", ToggleKitchenDystopia)
RegisterConsoleCommand("ChefApocalypse", ToggleKitchenDystopia)

print("[KitchenMayhem] Extra commands: KitchenDystopia / ChefApocalypse (toggles full game-changing mode)")